# Generated by Django 4.1.13 on 2024-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docketrun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('test', models.CharField(max_length=50)),
            ],
        ),
    ]
