# Generated by Django 4.1.13 on 2024-11-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docketrun', '0002_final_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_trial',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
