# Generated by Django 4.1.13 on 2024-11-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docketrun', '0003_final_trial_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='test',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
