# Generated by Django 4.1.13 on 2024-11-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docketrun', '0004_remove_employee_test_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Test',
            field=models.CharField(default='', max_length=50),
        ),
    ]
