# Generated by Django 4.1.13 on 2024-11-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docketrun', '0005_employee_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Test',
        ),
    ]
